/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package positivepractice;

/**
 *
 * @author Administrator
 */
public class FormPP extends javax.swing.JFrame {

    /**
     * Creates new form FormPP
     */
    public FormPP() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlPP = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        lblPrompt = new javax.swing.JLabel();
        lblQuote = new javax.swing.JLabel();
        lblQuoteImage = new javax.swing.JLabel();
        btnGenerateQuote = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTitle.setText("Positive Practce");

        lblPrompt.setText("Click the generate quote button in order to be inspired");

        lblQuoteImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/positivepractice/rainbow.png"))); // NOI18N

        btnGenerateQuote.setText("Generate Quote");
        btnGenerateQuote.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerateQuoteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlPPLayout = new javax.swing.GroupLayout(pnlPP);
        pnlPP.setLayout(pnlPPLayout);
        pnlPPLayout.setHorizontalGroup(
            pnlPPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPPLayout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addComponent(lblPrompt)
                .addContainerGap(126, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlPPLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblQuote, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(pnlPPLayout.createSequentialGroup()
                .addGap(175, 175, 175)
                .addComponent(btnGenerateQuote)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(pnlPPLayout.createSequentialGroup()
                .addGap(136, 136, 136)
                .addComponent(lblQuoteImage)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(pnlPPLayout.createSequentialGroup()
                .addGap(178, 178, 178)
                .addComponent(lblTitle)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlPPLayout.setVerticalGroup(
            pnlPPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPPLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(lblTitle)
                .addGap(18, 18, 18)
                .addComponent(lblQuoteImage)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(lblPrompt, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnGenerateQuote)
                .addGap(18, 18, 18)
                .addComponent(lblQuote)
                .addGap(48, 48, 48))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlPP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlPP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGenerateQuoteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerateQuoteActionPerformed
        int quoteNumber = (int)(Math.random()*16+1);
        switch (quoteNumber){
            case 1:
                lblQuote.setText("One");
                break;
            case 2:
                lblQuote.setText("Two");
                break;
            case 3:
                lblQuote.setText("Three");
                break;
            case 4:
                lblQuote.setText("Four");
                break;
            case 5:
                lblQuote.setText("Five");
                break;
            case 6:
                lblQuote.setText("Six");
                break;
            case 7:
                lblQuote.setText("Seven");
                break;
            case 8:
                lblQuote.setText("Eight");
                break;
            default:
                lblQuote.setText("Other");
                break;                
        }
    }//GEN-LAST:event_btnGenerateQuoteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormPP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormPP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormPP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormPP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormPP().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGenerateQuote;
    private javax.swing.JLabel lblPrompt;
    private javax.swing.JLabel lblQuote;
    private javax.swing.JLabel lblQuoteImage;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JPanel pnlPP;
    // End of variables declaration//GEN-END:variables
}
